server:
  port: 6666
spring:
  #  mvc:
  #    format:
  #      date-time: yyyy-MM-dd HH:mm:ss
  #      date: yyyy-MM-dd
  jackson:
    time-zone: GMT+8
forest:
  mvc:
    # 是否启用 xss 拦截
    enable-xss: true
    enable-trace: true
  log:
    ignore-text: "#该字段不打印#"
    ignore-req: ""
    ignore-resp: context
    package-path: org.qiqiang.forest.example.mvc.controller
    enable: true
  context:
    type: redis